version: '1'
name: medusa-backend

services:
  medusa-be:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: medusa-be
    restart: always
    depends_on:
      # ['postgres']
      postgres:
        condition: service_healthy
    volumes:
      - backend_data:/app/medusa/node_modules
    ports:
      - '9005:9000'
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://postgres:XXXX@postgres:5432/my-medusa-store

  postgres:
    image: postgres:16-alpine
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    expose:
      - 5432
    volumes:
      - C:\Program Files\PostgreSQL\16\data:/var/lib/postgresql/data
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: XXXX
      POSTGRES_DB: my-medusa-store
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: medusa@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  backend_data:
  postgres_data:
  pgadmin-data:

